name: verification de index.html

on:
  push:
    branches:
    - main
    - release/*

jobs:
  check-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify index.html exists
        run: |
          if [ -f "src/frontend/index.html" ]; then
            echo "::notice title=Check Passed::index.html existe"
          else
            echo "::error title=Check Failed::index.html manquant"
            exit 1
          fi
